title: CSES Analyses
description: Solutions and explanations for CSES problems
baseurl: "/cses-analyses" # repo name
url: "https://phuongdinh1411.github.io"

# Contact information
author:
  name: "Phuong Dinh"
  email: "phuongdinh1411@gmail.com"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-toc

# Sidebar configuration
sidebar:
  nav: "main"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: simple
      sidebar:
        nav: "main"
  - scope:
      path: "problem_soulutions"
      type: "pages"
    values:
      layout: simple
      sidebar:
        nav: "main"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: [1,2,3]
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false