title: CSES Analyses
description: Solutions and explanations for CSES problems
baseurl: "/cses-analyses" # repo name
url: "https://phuongdinh1411.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-toc

# Sidebar configuration
sidebar:
  nav: "main"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: simple
      sidebar:
        nav: "main"
  - scope:
      path: "problem_soulutions"
      type: "pages"
    values:
      layout: simple
      sidebar:
        nav: "main"

markdown: kramdown